#%RAML 1.0 Trait
headers: 
  authorization:
    type: string
    required: false
    description: Authorization header including Domain, username, and token obtained on login
    example: "Loyalty john.smith@example.com:799d463f16c967837c861f563e54a89f5d8a8e2bf00e321f"